name: Android Build

on:
  push:
    branches:
      - main  # Trigger the workflow on push or pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install
        working-directory: ./react-native-video-controls

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Update versionCode
        run: |
          VERSION_CODE=$((`grep versionCode ./YOUR_APP_DIRECTORY/android/app/build.gradle | awk '{ print $2 }'` + 1))
          sed -i "s/versionCode .*/versionCode $VERSION_CODE/" ./react-native-video-controls/android/app/build.gradle
          
      - name: Build AAB
        run: ./gradlew bundleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
        working-directory: ./react-native-video-controls/android

      # - name: Upload AAB
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: app
      #     path: react-native-video-controls/android/app/build/outputs/bundle/release/app-release.aab
